### ISSUE TITLE
set `develop` as default branch

### ISSUE THREAD

**Issue by joAschauer** [agoenergy/ptx-boa#115]
@markushal @wingechr before I do this I wanted to ask you quickly: is it okay for you to set `develop` as the default branch of this repository? 

This would have these advantages:

- pre-commit autoupdates PRs are based on develop
- we can use [closing keywords to automatically close issues based on merged PRs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- new PRs are automatically based on `develop`

**Comment by markushal** [comment]
i think that is a good idea
