### ISSUE TITLE
Bug: Only one bar in cost comparison plots

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#129]

**Comment by joAschauer** [comment]
I found the problem in while doing other stuff. In aggregate_costs https://github.com/agoenergy/ptx-boa/blob/bf901f6fe09bfa75797aca69b3e24e2e032a293f/app/ptxboa_functions.py#L93-L103

the aggregation is always done over the source regions and I passed it to `calculate_results_list()` in 52010d3

I can fix this
