### ISSUE TITLE
export dataframe to excel file

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#167]
add a button below each dataframe that allows to download as excel file

**Comment by joAschauer** [comment]
@markushal also for cost results dataframes?

**Comment by joAschauer** [comment]
why not downloading as .csv? you can open a csv with excel as well and with any other program too.

**Comment by markushal** [comment]
> why not downloading as .csv? you can open a csv with excel as well and with any other program too.

because if you download a csv file and open it in excel, this happens:

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/7d57fff4-cf7f-4276-bd57-acb33085cdfb)

You can open csv files in excel, but you need click through a csv import menu to do it which is not very comfortable

**Comment by markushal** [comment]
> @markushal also for cost results dataframes?

yes
