### ISSUE TITLE
market scanning: no highlight of own region if subregion is selected

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#209]
fix: highlight region instead

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/89246bf5-dff9-4610-b2de-abaef6f02093)

**Comment by joAschauer** [comment]
@markushal a possible fix would be to include the selected subregion in the plot. There is the `keep` argument in [`remove_subregions()`](https://github.com/agoenergy/ptx-boa/blob/822179e8b4af67187c5e0b2b26a44334612ef5ea/app/ptxboa_functions.py#L442) introduced in #411

**Comment by markushal** [comment]
> @markushal a possible fix would be to include the selected subregion in the plot. There is the `keep` argument in [`remove_subregions()`](https://github.com/agoenergy/ptx-boa/blob/822179e8b4af67187c5e0b2b26a44334612ef5ea/app/ptxboa_functions.py#L442) introduced in #411

thanks, that sounds good. I will try it out.
