### ISSUE TITLE
Display interest rates in percent

### ISSUE THREAD

**Issue by joAschauer** [agoenergy/ptx-boa#261]
It was proposed to display interest rates in % as it might improve readability. We need to discuss where to change it:

#### Option A:
Change it only where it is displayed to users, backend still uses decimals:

- https://github.com/agoenergy/ptx-boa/blob/2f1306aa6f5cdb21662d780f107d40b80bc02abd/app/ptxboa_functions.py#L216 returns interest rate in [%]

- https://github.com/agoenergy/ptx-boa/blob/2f1306aa6f5cdb21662d780f107d40b80bc02abd/app/ptxboa_functions.py#L473 transforms user input interest rate in [%] back to [decimals]

- https://github.com/agoenergy/ptx-boa/blob/2f1306aa6f5cdb21662d780f107d40b80bc02abd/app/ptxboa_functions.py#L449 transforms  [decimals] to [%]  on the copy of `st.session_state["user_changes_df"]`

#### Option B:
change it throughout the app, also in the database to percent. This would involve a lot of changes

**Comment by markushal** [comment]
also for other parameter, eg. mass:

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/f13f3051-3abf-4d52-bdc4-faaa29b204d5)
