### ISSUE TITLE
Transport distances to EU 

### ISSUE THREAD

**Issue by joAschauer** [agoenergy/ptx-boa#266]
Shipping distance from South Africa to the EU according to BOA: 1,104km; to Germany: 11,790km. The former looks very much like an error.

In general, distances to EU seem to be too small.

**Comment by suskrie** [comment]
There seems to be a general bug with the distance settings to the EU: 
In the 2nd graph on the market scanning sheet, it seems that the distance to the EU does not change but is fixed at the two values: 
- 1104 km for shipping distances 
- 2000 km for pipeline distances 

I would suggest to use transport distances to France as reference values for transport distances to the EU. 
If you tell me, which file you draw them from @markushal or @joAschauer, I can fill them in.

**Comment by joAschauer** [comment]
currently hard-coded here:
https://github.com/agoenergy/ptx-boa/blob/2e428ea6997dc9679b0e3c4f2798315f058b25a6/app/tab_market_scanning.py#L192-L195

info from @suskrie:
- we can use distances to Spain for EU
- projected demand is 20Mt for EU

@markushal can you do this?

**Comment by suskrie** [comment]
just one correction: the idea was to use distances to France (not Spain) for EU transport values
