### ISSUE TITLE
Update prices to USD/2023

### ISSUE THREAD

**Issue by joAschauer** [agoenergy/ptx-boa#267]
Inflation from last two years certainly has an effect on prices. This should be updated in all places whenever applicable.

**Comment by suskrie** [comment]
I updated the prices to USD2023 in a new version of the data excel file (2024-01-30_context_data_for_webapp.xslx) 
Also, Roman wanted to double check and update costs/prices in the entire tool to USD2023. I asked him to check the values in this context. I will let you know when he is done with this I guess (can't find him in here on github)

**Comment by markushal** [comment]
closed in favor of #423
