### ISSUE TITLE
clarify definition of storage capital costs

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#311]
how are storage capital costs defined? per storage capacity (USD/kWh) or per charge capacity (USD/kW)?

I would strongly prefer USD/kW, because for H2 storage storage capacity will be non binding, and we will invest in charge capacity, not in storage capacity. 

Accordingly, the "CAP_F" factor of storage that is returned by the ``optimize`` function should be defined as charge capacity per final product demand. I changed this in 032278276e6d119d8506ebb46591300757453fbe.

**Comment by markushal** [comment]
@wingechr I just checked in the excel, the costs Christoph reports are in USD/kW, which is fine. 

But I did not get how they are passed to the tool? the ``optimize`` requires this as part of the ``input_data`` dict:

````
            "EL_STR": {
                "EFF": 0.544,
                "CAPEX_A": 0.385,
                "OPEX_F": 0.835,
                "OPEX_O": 0.501
            },
            "H2_STR": {
                "EFF": 0.478,
                "CAPEX_A": 0.342,
                "OPEX_F": 0.764,
                "OPEX_O": 0.167
            },
````

but I cant find the strings ``EL_STR`` or ``H2_STR`` anywhere in the csv files in the ``data`` folder. 

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/47a8233a-df81-40aa-9fd8-4266b1ab0bd1)

**Comment by wingechr** [comment]
in the data, the keys are `H2-STR` and `EL-STR` (with a dash, not underscore).

Maybe we can fix this later. Initially, all the codes used "-", not "_".

But these will not work as python variable names.
