### ISSUE TITLE
fix errors of integrated flh optimizer

### ISSUE THREAD

**Issue by wingechr** [agoenergy/ptx-boa#312]
Hi @markushal .

This is the new branch https://github.com/agoenergy/ptx-boa/tree/fix-optimizer-integration
where the flh optimizer is enabled by default.

This breaks a few tests, but that is ok (changed values)

But, running `streamlit run ptxboa_streamlit.py` causes a lot of errors.

![grafik](https://github.com/agoenergy/ptx-boa/assets/4265368/b8857b8e-3575-4830-a00a-c4ba3c5e7614)

This is probably because the optimizer is not feasible:

![grafik](https://github.com/agoenergy/ptx-boa/assets/4265368/beb213dc-12d1-4e75-a30d-b80da3b09a3e)

Thisis maybe because of missing input data?

![grafik](https://github.com/agoenergy/ptx-boa/assets/4265368/693ffd6c-8a08-4b86-8829-f7d8ccb17722)

Lets discuss.

**Comment by markushal** [comment]
closed via https://github.com/agoenergy/ptx-boa/pull/322
