### ISSUE TITLE
only call optimize for currently selected country pair and settings

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#313]
``calculate_results_single`` is called here:

https://github.com/agoenergy/ptx-boa/blob/025073f54c9a07773707082465cd27ea852a40ec/app/ptxboa_functions.py#L105-L114

at this point, can you set ``optimize_flh = True`` for the currently selected country pair and settings, and ``False`` otherwise? That should do the trick

**Comment by markushal** [comment]
I think you would need to pass ``optimize_flh: bool = True`` to ``ptxboaAPI.calculate()``,

**Comment by wingechr** [comment]
implemented in d5db45bd and 0f0a22c
