### ISSUE TITLE
fix caching logic

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#329]
@wingechr There are some weird things going on in the app: 
- When the app starts, I think the calculate_results_single function gets executed twice (?)
- When choosing settings for which cashed results exist, the contents shown in the optimization tab are not updated

Can you check this? We can take a look at it together, if you prefer that

**Comment by wingechr** [comment]
to the second point:

the code 
```python
# todo: for debugging, temporarily pass network to session state:
st.session_state["network"] = network
st.session_state["model_status"] = opt_output_data["model_status"][1]
```
is not called because the streamlit caching prevents that the entire function is called.
(if a new country is selected, the optimization tab is updated. if you go back to a previously selected country, nothing happens, because the function is not called and so the session_state is not changed)

**Comment by wingechr** [comment]
@markushal in d61ce35,I disabled streamlit caching.

Now, optimization tab is updated, but its very slow because the app sends a LOT of redundant calls to the API

**Comment by joAschauer** [comment]
Regarding the network caching, I have the following thoughts: If we want to show the Network netcdf in the app, we have to save it with the same mechanism as done with the optimization result (can use the same hash but different suffix). Then the network has to be loaded and the `xarray` object has to be returned by `api.calculate()` to the front end. `api.calculate()` can e.g return a tuple[data, network], if no network is returned, the second entry is `None`

**Comment by markushal** [comment]
> @markushal: `calculate_results_single` is called twice, once with `'output_unit': 'USD/MWh'` and once with `'output_unit': 'USD/t'`.
> 
> once the caching works properly, this should no longer be an issue because it does not affect the optimization

I see. Even if it does not affect the optimization, wouldnt it be more efficient to do the unit conversion by just scaling the results with a product specific mass to energy coefficient, instead of doing the whole calculation twice?

**Comment by markushal** [comment]
> @markushal in [d61ce35](https://github.com/agoenergy/ptx-boa/commit/d61ce35e46d9ffef1608f5d2a80d1a5b95fa1241),I disabled streamlit caching.
> 
> Now, optimization tab is updated, but its very slow because the app sends a LOT of redundant calls to the API

that does not sound like a good solution :(

**Comment by markushal** [comment]
> Regarding the network caching, I have the following thoughts: If we want to show the Network netcdf in the app, we have to save it with the same mechanism as done with the optimization result (can use the same hash but different suffix). Then the network has to be loaded and the `xarray` object has to be returned by `api.calculate()` to the front end. `api.calculate()` can e.g return a tuple[data, network], if no network is returned, the second entry is `None`

That sounds like a good idea! That would also mean we do not need to save the network to session state. @wingechr can we implement it like this?

**Comment by wingechr** [comment]
the caching of the network is already implemented, but it should not always be loaded. 
loading the saved network is rather slow, so we only want to do it sometimes.
Also, this is only temporary for the optimization tab, so I would not want to change the API for that.

I think there should be a separate api call to get the network data. 
I will look into it tomorrow

**Comment by markushal** [comment]
@wingechr can this be closed?
