### ISSUE TITLE
Use less tabs

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#352]
they take up too much horizontal space.
- move literature to bottom of info tab
- rename "Certification schemes" to "Certification"

**Comment by markushal** [comment]
@joAschauer maybe replacing tabs with buttons would also help, if these buttons could be arranged in more than one row

**Comment by joAschauer** [comment]
we could use streamlit-antd-components buttons. They wrap to more than one line if the window is too small to display all buttons in one line. I think you already used them for the deep dive country selection.
