### ISSUE TITLE
check costs of energy carriers

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#365]
I just noticed that the heat costs are quite significant and checked the specific costs of materials and energy carriers:

- Are heat costs ok?
- also: are bunker fuel costs ok? seems very low compared to heat costs

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/1f7a04d7-b4ab-4344-b02e-d377ef96331b)

**Comment by joAschauer** [comment]
bunker fuels?
