### ISSUE TITLE
H2 reconversion: weird cost increases

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#367]
@wingechr thanks for fixing the h2 reconversion bug!

However, when I compare the costs of a chain with and without H2 reconversion:
- costs with reconversion are higher than without (that is good)
- but relative cost increases across cost categories are very uneven. Example screenshot: transportation costs factor 5, much higher that the other categories. 

Cost increases are caused by low efficiency of the reconversion process, so this is strange. 

I also could not find the efficiency of the reconversion process in the input data tab. 

Can you check this?

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/eff1213e-2c14-41f9-a834-2fa5d491ad50)

**Comment by markushal** [comment]
@joAschauer fyi

**Comment by wingechr** [comment]
As Jo pointed out, the problem is that we only use the optimized data for the current selection. We have to enable using the optimized data for ALL requests

**Comment by wingechr** [comment]
also, i think the reconversion is lumped in the transportation costs?
