### ISSUE TITLE
app on streamlit cloud does not update

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#38]
@wingechr thanks for merging my latest PR and for syncing it to your fork. But it seems that the app on streamlit cloud has not been changed. Can you look into that? For example, there should be a new sheet called ``Input data``.

**Comment by wingechr** [comment]
for some reason i still have to reboot it manually (maybe I can eventually figure out how to automate that).

just rebooted

**Comment by markushal** [comment]
I am closing this now - in the past I had no problems with updating the app
