### ISSUE TITLE
add maps for deep dive countries

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#40]
We want choropleth maps for the three deep dive countries (Argentina, Morocco, South Africa) that show costs per subregion. Like the world map in the dashboard. 

But for the subregions we need to define shapefiles, I guess. @wingechr could you take a look at that?

For the world map I used plotly express which has built-in shapes for countries, but not for subnational regions. It would be fine for me to switch to another mapping frontend if that helps.

**Comment by joAschauer** [comment]
@markushal you can use data from Natural Earth: https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/
