### ISSUE TITLE
pass DAC and water desalination parameters to optimize function

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#406]
We need the parameters of these two processes to be passed to the optimize function, if they are selected in the settings as sources for co2 and water (instead of specific costs). @joAschauer @wingechr could you implement this, please? 

I think you would need to make changes here

 https://github.com/agoenergy/ptx-boa/blob/b93cc7aaf706a98c4dcca272cd5bf66caa125ef5/ptxboa/api_optimize.py#L236

and here

https://github.com/agoenergy/ptx-boa/blob/b93cc7aaf706a98c4dcca272cd5bf66caa125ef5/flh_opt/_types.py#L62

I created a branch and PR where I will adapt the optimize function once you provide the data: https://github.com/agoenergy/ptx-boa/pull/405

**Comment by joAschauer** [comment]
@wingechr can you do this?

**Comment by wingechr** [comment]
@markushal should work now.

if specified, the data for the optimize() function should contain 2 new entries like this:

```python
{
    "H2O": None,
    "CO2": {
        "CAPEX_A": 0.07726085034488815,
        "OPEX_F": 0.0356900588308774,
        "OPEX_O": 0,
        "CONV": {"EL": 0.4515, "HEAT": 1.743},
    },
}
```
