### ISSUE TITLE
The selected button for deep dive country looks weird:

### ISSUE THREAD

**Issue by wingechr** [agoenergy/ptx-boa#418]
![grafik](https://github.com/agoenergy/ptx-boa/assets/4265368/604e7ecd-9b0b-46cb-b1fc-8d58a1d82a73)

**Comment by joAschauer** [comment]
cannot reproduce, works for me both locally and on the server. Maybe an issue with the browser?

**Comment by wingechr** [comment]
on my system i have the same issue in firefox and chrome, on the productive server.

**Comment by markushal** [comment]
on my system the button looks fine
