### ISSUE TITLE
anpassen auf 2023er values

### ISSUE THREAD

**Issue by christoph-heinemann** [agoenergy/ptx-boa#423]
Hi Markus
wir müssen mit ROman (wenn er nächste Woche zurück ist) mal noch sprechen, ob er eigentlich die daten alle auf 2023 angepasst hatte vor seiner Elternzeit. Mir ist nicht so. Dafür müsste man alle Values nochmal mit einem Deflator verknüpfen. 
Grüße
Christoph

**Comment by markushal** [comment]
@wingechr, do you know if this has already been addressed? maybe linked to #296 ?

**Comment by markushal** [comment]
#267 also seems to be linked to this. @suskrie, do you know what the status is on this issue?
