### ISSUE TITLE
flh pv hybrid > flh pv ?  

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#429]
I just noticed that in some cases the FLH of PV for hybrid sites is larger that the one for PV only sites. Does that make sense?

![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/3f48f41d-17c0-4507-a99c-6b78b0ecf1d0)

**Comment by joAschauer** [comment]
This is theoretically possible with our methodology. We use Q0.95 for wind onshore and hybrid and Q0.90 for PV. Therefore, there is still a 10% chance that the hybrid location will be at a point where the PV is higher than at our pure PV sample point. You think that is a problem?

**Comment by markushal** [comment]
> This is theoretically possible with our methodology. We use Q0.95 for wind onshore and hybrid and Q0.90 for PV. Therefore, there is still a 10% chance that the hybrid location will be at a point where the PV is higher than at our pure PV sample point. You think that is a problem?

I see. It is surprising, but it is good to hear that it is in line with our methodology. What was the reason again for choosing different quantile thresholds for the different site categories?

**Comment by joAschauer** [comment]
We increased the percentile for Wind onshore and hybrid to 0.95 because for these technologies, FLH had a negative bias compared to the Excel tool when using 0.9

**Comment by markushal** [comment]
I see. Then we just leave it like this. The differences are not that large anyways, luckily.
