### ISSUE TITLE
Only calculate costs that are displayed

### ISSUE THREAD

**Issue by joAschauer** [agoenergy/ptx-boa#453]
We are often unnecessarily calculating costs with every script rerun. If we would only calculate the costs that we want to display in the currently active tab, we likely get a better performance and user experience.

Only the following tabs need calculated costs:
- "Costs":
    - needs cost comparisons over all dimensions (per region, per scenario, per chain per res_gen) with and without user modifications
    - doesn't need all subregions, only selected subregion
- "Market scanning"
    - only needs costs per region with user changes 
    - doesn't need all subregions, only selected subregion
- "Deep dive countries"
    - only needs costs for all subregions of the currently selected deep dive country 

In the "Input data" tab, the costs are not needed, but I am not sure what should happen if a user modifies input data. We could change the button "Apply changes" to "Register changes" and modify the help text as follows:

> You can edit data directly in the table. When done, click the Register changes button below. If you switch to one of the tabs "Cost", "Market Scanning" or "Deep Dive Countries", results will be recalculated.

@markushal what do you think about this?

**Comment by markushal** [comment]
I think we tried this before and ran in some problems, but I cant find the old issue. It sure sounds like a good idea! Also the procedure with registering changes sounds fine.
