### ISSUE TITLE
use 2.0 as version for launch

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#483]
because the excel tool was 1.0

**Comment by markushal** [comment]
- [ ] and remove draft version warning
![grafik](https://github.com/agoenergy/ptx-boa/assets/26714648/ad25ff13-1fa6-4ae1-9132-4c6e6df7c5c9)

**Comment by markushal** [comment]
@joAschauer if you fix #495 anyway, can you also bump the version to 2.0?

**Comment by joAschauer** [comment]
🚀
