### ISSUE TITLE
Tab Certification | Structural edits 

### ISSUE THREAD

**Issue by suskrie** [agoenergy/ptx-boa#58]
- [x] Adjust heading of What's this - delete space before ** (so that html language takes effect) 
- [x] In the selection menu: Write the names of the frameworks in full (and abbreviations in brackets)
- [x] Provide information on certification frameworks in individual elements that can be "folded out" (as in sustainability tab)
My suggestion to structure this would be into: 
1. Characteristics 
2. Scope of application
3. Sources 
- [x] If no information is available, 
1. Section: Characteristics "not specified" instead of nan
2. Section: Scope of application: shows no results if nan
- [x] Add info button to headline "Life cycle scope"

> Well-to-gate: GHG emissions are calculated up to production. Well-to-wheel: GHG emissions are calculated up to the time of use. Further information on the life cycle scopes can be found in IRENA & RMI (2023): Creating a global hydrogen market: certification to enable trade, pp. 15-19

- [x] Add info button to headline "Geographical scope" 

> This field provides an answer to the question: if you want to address a specific country of demand, which regulations and/or standards exist in this country that require or allow proof of a specific product property?

**Comment by markushal** [comment]
@suskrie in streamlit, there is no info button without an interactive element, but i added the infotexts as texts in the characteristics section.
