### ISSUE TITLE
Adjust "What's this?" info box in all tabs

### ISSUE THREAD

**Issue by suskrie** [agoenergy/ptx-boa#63]
Suggestion: instead of "What is this?" I would suggest using he **…** titel of each sheet 
This would help to navigate and give more incentive to read and unfold the boxes

e.g. Instead of 
**"What's this?"**
**Get supplementary information on PTX-relevant sustainability issues** 
[...text] 
directly 
**Get supplementary information on PTX-relevant sustainability issues**
[...text]

**Comment by markushal** [comment]
@suskrie Honestly, I prefer it the way it is. We already have several headers directly below each other (the title of the app, the title of the tab, and the title of the information below the "What is this?" expander. I would like the expander to not convey information as long as it is closed, but still invite people to expand it if they want to know more.
