### ISSUE TITLE
integrate "What's in, What's out?" information 

### ISSUE THREAD

**Issue by suskrie** [agoenergy/ptx-boa#64]
in the excel tool, we integrated information on "what's in, what's out?" in the tool's assumptions. 
we did this by placing a button "more info on cost components" in every sheet where this info is relevant. 
![grafik](https://github.com/agoenergy/ptx-boa/assets/149697156/7f66f270-e856-46a9-9d5d-83a8918695b2)

suggestion: place an info button (?) where the information on "what's in, what's out?" pop up in a window if clicked upon. 
![grafik](https://github.com/agoenergy/ptx-boa/assets/149697156/0c8f9a93-2c21-4ad2-8e09-aba79fb6b24a)

relevant sheets would be in my view
- dashboard 
- cost by region 
- deep-dive countries

**Comment by markushal** [comment]
closed in favour of #62
