### ISSUE TITLE
new team member

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#66]
Hi @RichChang963,

can you please add our colleague Susanne Krieger (github handle ``suskrie``) to our team and give her developer access to this repository?

**Comment by RichChang963** [comment]
Hi @markushal,

We added her into the repository, and she shall receive the invitation. Kindly let us know if she has problem to access.

Best Regards,
Yu-Chi

**Comment by markushal** [comment]
Thank you!
